services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env
      - backend/.env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki:latest

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml

volumes:
  grafana_data: